# image,docs: https://hub.docker.com/_/wordpress/

version: '3.3'

services:

  wordpress:
    image: wordpress:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
      - ${APP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${DB_MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${DB_MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_MYSQL_NAME}
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html

  mysql:
    image: mariadb:${DB_MYSQL_VERSION}
    container_name: wordpress-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}


volumes:
  wordpress:
    driver: local
  mysql:
    driver: local
    
networks:
  wordpress:
    driver: bridge
